### ISSUE TITLE
You will need to change the law if I am correct

### ISSUE THREAD

**Issue by tinjaw** [deptofdefense/code.mil#14] opened 2017-02-24 01:16 UTC
I am a government employee. I write software. Everything I write is PUBLIC DOMAIN. I tried many many times to use a license (any license) and was told by the Army lawyers that by law it is PUBLIC DOMAIN and can not be put under any license. One example was during the APPS for ARMY contest. I was told that I had no choice. I could not license it in any way.

How is this proposal different? Is anybody reading this a lawyer? If so, can you provide us the documents that support what I have been told?

**Comment by tomberek** [comment] 2017-02-24 06:34
@tinjaw The law has not changed, your work is still Public Domain from a copyright perspective. That is why this agreement exists, it uses a contract law, rather than copyright law, to establish a situation which would normally be handled by using an existing open source license.

@shawoods : you may have some comments.

**Comment by marctjones** [comment] 2017-02-24 13:45
The problem with using contract law instead of relying on a license is that you really can't do that successfully. And frankly I do not understand even why you would want to. What is the motivation for trying to impose a FOSS like license via contract law. Why is there an objection to having the code unfettered in the public domain. Isn't what you are trying to do here restrict American's rights to use public domain material? Isn't that in direct opposition to the public policy of putting the works of the federal government's in the public domain.  

Further I think it is strange to do this under the cover of a FOSS license like agreement. Since the whole point of FOSS is to give people rights that don't exist by default under copyright law. Public domain material is the FOSS-y way of doing that. I think most FOSS proponents would argue that in an ideal world all code would simple be in the public domain and eliminate the need for the issues that come with licensing. Why would you want to restrict people's rights to use public domain material? What is the objective of trying to impose a FOSS like agreement on users of government works? How is this better than a simple public domain dedication to resolve the case of the legal status of the copyright in foreign jurisdictions.

How do you think this is accomplished legal to do if you acknowledge that  the code remains in the public domain? Can't I simple avoid this agreement by simple refusing to consent to the agreement and taking the code as a public domain work? I note that you do mention consideration which is indeed a prerequisite for forming a contract in American law. But you seem to be overlooking consent. You can not simply impose an obligation to consent. That would not be consent at all.

You see in many FOSS licenses that the license says it presumes people take the code under the license, but that only works because individuals have to choose between accepting the license or violating the author's copyright. The copyright holder gives others the choice between being liable for copyright infringement or agreeing to comply with the license.  But here no such choice exists. You asking users to choose to accept a contract to use the public domain software, or simply use the software as a public domain work without accepting the contract. Why would anyone simply not choose the later in every case?

Since the work is in the public domain doesn't even the contract theory fail because there is no consideration offered on the government's behalf. Offering up the right to use a work already in the public domain as consideration appears to be offering nothing at all. In that case this agreement is an illusionary contract and unenforceable. (https://en.wikipedia.org/wiki/Illusory_promise)

**Comment by paragonie-scott** [comment] 2017-02-24 14:52
> What is the legal theory behind the enforcement of this agreement since you acknowledge that the code remains in the public domain?

The problem with public domain is that other jurisdictions do not recognize it in their own local enforcement of copyright law, so effectively by virtue of living in these jurisdictions you're effectively violating the copyright laws.

That has prompted the existence of CC0 and other licenses.

Attaching a public license to public domain code might seem silly, but unfortunately that's a necessary step for foreign contributors to navigate their own legal system with minimal liability (where "minimal" hopefully means "zero").

**Comment by marctjones** [comment] 2017-02-24 14:57
Isn't that situation better addressed by a simple public domain dedication rather than trying to enforce a contract?

Or simply stating that where this work is not in the public domain it is licensed under the terms of a existing FOSS license? (Although that case seems like it could get confusing really quick, which is probably why most other agencies have opt for simply doing a public domain dedication or using the CC0).

**Comment by johnmod3** [comment] 2017-02-24 15:00
we went thru a long discussion on this when Army Research Lab came out with their OSS policy. they we trying to create their own OSS-type license agreement as well. see https://github.com/USArmyResearchLab/ARL-Open-Source-Guidance-and-Instructions 
and eventually came to CC0 1.0 Universal 
License proliferation isn't the best thing for the OSS community : https://en.wikipedia.org/wiki/License_proliferation

**Comment by shawoods** [comment] 2017-02-24 17:14
You are all raising very valid issues and questions. 

First, I want to provide our perspective about “public domain.” The idea that U.S. law requires Federal government employees to put creative works in the public domain is a bit of an overstatement. The U.S. Copyright Act does not explicitly define public domain. What the Act actually does is make works created by U.S. Federal government employees ineligible for copyright protections (17 U.S.C. 105). The purpose of section 105 is to prevent the U.S. government from using copyright to impose restrictions on the public’s access to and use of these creative works. Public domain is generally understood to refer to creative materials that are not protected by intellectual property laws such as copyright, trademark, or patent laws. Not all countries acknowledge the concept of public domain.

Second, the legal framework that makes works created by U.S. Federal government employees ineligible for copyright protections (17 U.S.C. 105) was written long before the invention of software. The first statute on point was as early as 1895 and then again in 1909 and finally recodified in 1976. Creative works at that time were mostly static -- maps, publications, compendiums. Software is a vastly different animal than maps or publications. Software constantly evolves with each contribution potentially having a different copyright and license status. 

Third, merely placing source code in the public domain with CC0 1.0 does not address how contributions will affect the openness of the project over time. We think the open source and free software communities have made incredibly important progress on how to keep code freely available to the public as the code evolves. 

The draft agreement relies on contract theory instead of copyright law. It’s more like a terms of service with the idea being that the applicable terms are the open source license associated with the project repository (e.g., MIT, BSD-3, Apache 2.0). The contribution process, by using the Developer Certificate of Origin, would likewise be licensing the developer’s contribution under the same license. Part of the reason for this approach is to avoid adding to the license proliferation problem.

We readily admit that the agreement is not perfect, which is why we released it as a draft for comment from the community. We appreciate your feedback and any suggestions on how to make the agreement better!

**Comment by blakelapierre** [comment] 2017-02-24 18:41
Why is the US government providing different guidance on this issue to different people? tinjaw says that Army lawyer's were very explicit about being unable to license code, but here is the Dept. of Defense claiming otherwise?

**Comment by sephcoster** [comment] 2017-02-24 20:11
First - Thanks for having this discussion in the open 👏   and thanks for your replies to date.

Can you explain more about the Contract Theory approach and the use cases it addresses that are not already addressed by the approaches  (many CC1.0) of 18F, Code.gov, CFPB, NASA, etc? 

What kinds of scenarios / contribution models would the proposed differences help solve for / promote? Should other government organizations using CC1.0 or other more widely adopted licenses be taking these into account?

**Comment by tinjaw** [comment] 2017-02-24 22:25
BTW, As a DoD organization, you fall under the DODCIO. And the CIO says that [existing OS licenses are good enough](http://dodcio.defense.gov/Open-Source-Software-FAQ/#Q:_What_license_should_the_government_or_contractor_choose.2Fselect_when_releasing_open_source_software.3F). As a Department of the Army civilian, I need to follow Army rules and regulations. If I am following "my commander's guidance" I am more likely to get approval.

Right now my "chain of command" via that webpage says "Public domain where required by law.  You must release it as "public domain" (when releasing it at all) if it was developed by a US government employee as part of their official duties."

As a worker bee I need something with a signature on it that I can point to when explaining my actions.

**Comment by missyk5150** [comment] 2017-02-26 20:16
If we were in the casino on the computers ran by 0ld(amd) now (intel) the surveillance software they are not allowed to do visual and audio unless an officer of the non-federal but the state is present. Any one who understands more than me about the way to write and do these codes can help the idea here. From what I noticed it's as if the Federal licence makes it so the gov here can not outright ask for a civillian to do this but if someone has a post with a graphic picture . They may have the right to be able to protect or mark claim to the contributions they made... to say they would like sourcecode to or creative commons to assist in the rights or being a citizen to not categorize the works with the Federal works that they are contributing posts and discussing them with. its also a possibility to repost the whole federal work as your exampke of what the problem is to solve and to get help..  but then do a sign out and a sourcecode and a GNU and a creative commons licence at the end of the  material that needs the help to resource and re.cru.it the material as a piece  that you redid or made your own way in your whole work.then source the hell outta that.  This will make it reavailable for the Federal gov to use as the same kind they have been using since the start.   but revamped to suit the specific ideas that they could not do federally when it was without a civillians rights attached. ...... Wish i knew how to talk with the fancy words y'all use but I am a novice but my mentor worked for E.G.&G. EDGERTON GRIER AND GERMAINHAUSER??? IN SANTA BARBARA. BACK WHEN ALICE COOPER WAS STILL FLYING ON TOUR IN HIS LEER JET. THE EG&G IS NOW THE NSA & DOD THEY ARE VERY SPECIALIZED AND INTELLIGENT .. FOR ALL THE U.S. WE GET TO HAVE THIS LEVEL Q PROTECTION HIGHEST ON THE BOARD OF SECURITY IN THE WORLD.. THE U.S. PROVIDES THIS AND THE MILITARY TOO. IT IS GOOD TO BE HERE IN THE USA.

**Comment by storrgie** [comment] 2017-02-26 23:12
I for one think your contributions are really moving us forward @missyk5150

**Comment by enckse** [comment] 2017-02-26 23:18
I think we can all agree "IT IS GOOD TO BE HERE IN THE USA" is both true and only properly expressed in all caps, any lower case letters would not properly express the proper amount of patriotism.

Seriously, though, someone should probably reign this @missyk5150 thing in here

**Comment by missyk5150** [comment] 2017-02-27 06:04
Hey don't pick on me if you are I am sad. If you are not than i
misunderstood.  I am not here for ridicule I just don't know how to express
myself in a verbal manner as high level as you can. If your just going to
pick on people you will never get this project anywhere. It's about working
together. Sorry if you can't accept my CAPS ON.

**Comment by BrandonBouier** [comment] 2017-02-27 13:32
Everyone, let's keep this conversation on topic.

**Comment by shawoods** [comment] 2017-02-27 16:27
> Why is the US government providing different guidance on this issue to different people? tinjaw says that Army lawyers were very explicit about being unable to license code, but here is the Dept. of Defense claiming otherwise?

There are multiple organizations within the U.S. Federal government that provide guidance about open source and procured source code. Within that guidance and the law, however, there are many possible avenues to pursue. Intelligent minds will differ on the "best" avenue and every organization (for example, a research lab versus a program office) has unique circumstances that affect which option might make the most sense. This initiative is not intended to set DoD policy, but rather exploring alternate ways for joining the open source community.

> Can you explain more about the Contract Theory approach and the use cases it addresses that are not already addressed by the approaches (many CC1.0) of 18F, Code.gov, CFPB, NASA, etc?

Take a read on _ProCD, Inc. v. Zeidenberg_, 86 F.3d 1447 (7th Cir. 1996), which cites to U.S. Supreme Court case, _Feist Publications, Inc., v. Rural Telephone Service Co_., 499 U.S. 340 (1991).  There is some precedent in attaching agreements to public domain materials.

We think there is a lot of value in project maintainers being able to select the open source or free software license that makes the most sense for the project. CC0 1.0 is an option, but so is Apache 2.0 or GLPv3. We are exploring the feasibility of being able to select from a variety of widely adopted open source agreements rather than just being limited to one, but of course this is challenging because we don't have copyright.

**Comment by BrandonBouier** [comment] 2017-02-27 22:03
We've pivoted based on user feedback. Take a look at the current CONTRIBUTING.md

**Comment by fulldecent** [comment] 2017-02-27 22:07
The updated CONTRIBUTING states that a license is to be chose by specific agencies. In this light, this instant issue is now out of scope for this project. I recommend to close this issue.

Regarding whether public domain projects are allowed to restrict incoming contributions based on a CONTRIBUTING file, then yes they can.

**Comment by blakelapierre** [comment] 2017-02-27 22:28
>Within that guidance and the law, however, there are many possible avenues to pursue.

The issue opener was quite explicit about what they were told:

>I am a government employee. I write software. Everything I write is PUBLIC DOMAIN. I tried many many times to use a license (any license) and **was told by the Army lawyers that by law it is PUBLIC DOMAIN and can not be put under any license**. One example was during the APPS for ARMY contest. I was told that I had no choice. I could not license it in any way.

>There are multiple organizations within the U.S. Federal government that provide guidance about open source and procured source code. 

Maybe they should get together and give us a real answer?

**Comment by ckaran** [comment] 2017-02-27 23:35
@tinjaw Take a look at what ARL has [done](https://github.com/USArmyResearchLab/ARL-Open-Source-Guidance-and-Instructions).  There may be some help for you in there.  For what it's worth, I cowrote that policy and may be able to help you out.

@blakelapierre It is difficult to get a complete answer in all cases.  There are different laws governing different agencies, and then different regulations governing suborganizations within agencies.  As an example NASA is governed by the [National Aeronautics and Space Act](https://en.wikipedia.org/wiki/National_Aeronautics_and_Space_Act) and other acts, some of which don't apply to the DOD.  The DOD itself is broken into different services that are governed by different regulations, etc., etc. etc.  So what is true of one part of the US Government may not be true of a different part.

**Comment by blakelapierre** [comment] 2017-02-28 21:37
My understanding is the same as told in the opener. All US government work is public domain and completely owned by the people. I don't see how the US government can put a license restricting, or otherwise controlling, peoples' use of any text it, its employees, or its contractors produce.

Can anyone cite a particular statute that contradicts the Army's lawyer?

**Comment by jbjonesjr** [comment] 2017-02-28 22:17
@blakelapierre check out the discussion on this topic in #12.

**Comment by fulldecent** [comment] 2017-02-28 22:31
@blakelapierre The ARL recommends releasing under CC0, which specifically disclaims copyright. This is the same if you were to personally copy and paste other code you found on the internet that was properly licensed CC0 and then you relicensed it CC0. You can do that.

Next is a "restricting".

You can't restrict other people from using the published work as they see fit. That includes requiring them to include copyright notices in their files like MIT does. This is why I argue MIT is unsuitable for this US Government work (excluding NASA, NASA is special).

Lastly, we go to disclaimers. CC0 includes disclaimers. THIS IS IMPORTANT (see #36). If you release software and say "this code works for launching GPS satellites" (actually a goal of this project) and your software fails a launch mission because you have `if (a = b)` instead of `if (a == b )` (this actually happened, people died) then somebody might sue you. They might win that lawsuit because they will argue you provided code a launch something and somebody died following your instructions. This is why we use disclaimers when we release code, there is big uppercase lettering telling you that while we are releasing something to the public, we are disclaiming certain responsibilities.

That disclaimer process is related to your publishing of the project and is ENTIRELY ORTHOGONAL to you asserting copyright or other rights.

**Comment by shawoods** [comment] 2017-03-01 13:47
I've seen this in a few threads, but the concepts of lack of copyright, public domain, and CC0 keep getting conflated.

* U.S. law does not require Federal government employees to put creative works in the public domain. The U.S. Copyright Act does not explicitly define public domain. What the Act actually does is make works created by U.S. Federal government employees ineligible for copyright protections (17 U.S.C. 105). U.S. Federal works are copy-less.
* You cannot license copy-less works under copyright law because licenses presume copyright ownership. 
* Other agencies that use CC0 for Government works are not licensing the original Government work under CC0. Rather, in jurisdictions where the U.S. Government has copyright protections, the work is being licensed under CC0 to achieve a public domain dedication. These agencies are also asking that copyrighted contributions likewise be licensed under CC0. For many of you, I know this is old news, but I keep seeing the idea that Government works=CC0.  That's an inaccurate oversimplification of the problem set.

>Everything I write is PUBLIC DOMAIN. I tried many many times to use a license (any license) and was told by the Army lawyers that by law it is PUBLIC DOMAIN and can not be put under any license. 

@tinjaw I generally agree, but would state it a little differently. I would say that everything a U.S. Federal employee creates in the scope of their duties is not eligible for copyright protections. People in the U.S. generally understand that to mean the work is in the public domain. See second bullet above -- you cannot license Government works under copyright law because of the absence of copyright.

>I don't see how the US government can put a license restricting, or otherwise controlling, peoples' use of any text it, its employees, or its contractors produce.

@blakelapierre The U.S. Government cannot restrict people's use of or access to Government works via a license under copyright law. Our original strategy was using contract law as a bridge to using the terms and conditions of widely adopted open source licenses.  We've pivoted since then with the updated strategy that focuses on the contribution process instead.

>This is why I argue MIT is unsuitable for this US Government work

@fulldecent I may be taking your comment out of context, but under our updated strategy where the open source license is limited to copyrighted contributions (using the DCO process) and foreign jurisdictions where we have copyright, I see no limitations on the type of license we might use. The project maintainer would have the freedom of choice on which license to use based on the needs of the project. I also think the need for disclaimers is different for the federal Government than private parties, but I'll address that in #36.

**Comment by blakelapierre** [comment] 2017-03-01 19:00
I agree with many of the points being made since my last post, however, the [current proposal](https://github.com/deptofdefense/code.mil/blob/master/Proposal/CONTRIBUTING.md) requires contributors to state:

````
Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.
````

We have established here that the US Government cannot restrict use of any of its work, however if the contributors' Certificates are released as part of their contributions, the US Government will be making a claim about what others are allowed to do with the release.

I noticed that the [current proposal for licensing](https://github.com/deptofdefense/code.mil/blob/master/Proposal/LICENSE.md) indicates to use licenses that would restrict use of US Government work. Specifically, the MIT license has been called out as being incompatible, but it is still being proposed to use.

**Comment by shawoods** [comment] 2017-03-01 19:23
@blakelapierre The language you are quoting is from the DCO text. Anyone intending to use DCO must comply with the terms of the DCO license document. Our proposed strategy is to implement the DCO process for contributions. We can't change that language.

>...if the contributors' Certificates are released as part of their contributions, the US Government will be making a claim about what others are allowed to do with the release.

If we merge commits executed under the DCO process, the USG, just like everyone else, has to abide by the terms of the license invoked by the contributor in the DCO. 

>Specifically, the MIT license has been called out as being incompatible

This may have been stated, but it's not true.  Under our strategy, the license, MIT or otherwise, is not being applied against the Government written code, which has no copyright, but rather the copyrighted contribution or the code where it is eligible for copyright protections. 

Maybe your underlying concern is that the Government is stating that it will only accept contributions submitted under the license the USG specified?  There is no restriction on the USG's ability to state that it will only accept contributions under the license chosen for the project. Agencies working in open source routinely do this as does the open source community in general. There is no legal prohibition on the USG's ability to specify the conditions under which it will accept contributions from the public.  The fact that USG written code does not have copyright is a separate matter altogether.

**Comment by blakelapierre** [comment] 2017-03-02 07:25
That's fair, but I can't imagine the success of code that is multi-licensed. Having to write the liably-accurate manuals on what code is available (or, maybe, it turns out: it's not available to you for `x` technicality) under which license is a job that I think few will volunteer for.

I think the solution is simple: the `AS IS` license. Anything else is a lie or unnecessary. The code is the code and there is really no license that can stop someone from copying it and using it for their own purposes. I mean, *really*.

No license can guarantee anything other than `AS IS`. The machines are going to run the text they're given, not the text someone thought they were giving them.

Building some kind of verification and classification system of `AS IS` code would probably be interesting.

**Comment by blakelapierre** [comment] 2017-03-02 08:05
>Maybe your underlying concern is that the Government is stating that it will only accept contributions submitted under the license the USG specified? There is no restriction on the USG's ability to state that it will only accept contributions under the license chosen for the project. Agencies working in open source routinely do this as does the open source community in general. There is no legal prohibition on the USG's ability to specify the conditions under which it will accept contributions from the public. The fact that USG written code does not have copyright is a separate matter altogether.

I think the concern comes when the US Government republishes licensed code. I think we've established that all US Government publications are public domain, uncopyrightable, and/or unlicensable; meaning, anyone could do anything they'd like with any part of the publication they'd like. Now, we have reached a contradiction: anyone may freely "violate" any licensed code by virtue of their ownership of publications of the US Government, or the US Government published a not public domain work.

**Comment by marctjones** [comment] 2017-03-02 14:46
@blakelapierre In the typical case, no one, including the government gains, a copyright in a work merely because they republish it. Copyright is granted by the /act of authorship/ and is not, under the current law, dependent on the /act of publication./ To determine who the copyright holder is you need to look to who authored the work (and its subsequent history of changes in ownership/assignment if any.)

The government just like any private citizen can publish and republish copyrighted works without affecting the copyright status of the work. As long as the government has a license to publish the work, the government can do so without violating the copyright of the copyright holder.

I am not your attorney. This is not legal advice and is only intended to provide information. You should consult with an attorney if you need legal advice as the application of law depends on the facts presented in each situation. These are my views and not the views of my employer.

**Comment by marctjones** [comment] 2017-03-02 15:02
@blakelapierre It is actually very common for FOSS projects to contain source code licensed with different licenses. But you are right it can get complicated. You might want to check a recent presentation at FOSDEM on [Mixed License FOSS Projects](https://fosdem.org/2017/schedule/event/mixed_license/). Unfortunately it appears that there is no video for the talk but you can still see the slide deck.

You can also look the Software Freedom Law Center's advice on related to this situation. 
* [Maintaining Permissive-Licensed Files in a GPL-Licensed Project: Guidelines for Developers](http://softwarefreedom.org/resources/2007/gpl-non-gpl-collaboration.html)
* [Managing copyright information within a free software project](http://softwarefreedom.org/resources/2012/ManagingCopyrightInformation.html)

**Comment by marctjones** [comment] 2017-03-02 15:59
@shawoods  I feel like you can close this issue. This horse is pretty close to dead.

**Comment by shawoods** [comment] 2017-03-02 16:30
This has been a great thread. I think we've closed out all the issues, but if someone disagrees let me know and I can always reopen it.

**Comment by blakelapierre** [comment] 2017-03-02 21:05
>The government just like any private citizen can publish and republish copyrighted works without affecting the copyright status of the work.

What law allows this?

>What the Act actually does is make works created by U.S. Federal government employees ineligible for copyright protections (17 U.S.C. 105). 

A derivative work is a work. If the US Government publishes it. I can use it

The premature closing of this issue was really uncalled for.

**Comment by blakelapierre** [comment] 2017-03-02 21:11
>The draft agreement relies on contract theory instead of copyright law.

Contract theory is predicated on consideration. Is there a contribution payout schedule somewhere? Will payments be negotiated per contribution?

**Comment by marctjones** [comment] 2017-03-02 23:55
@blakelapierre You will note that they have pivoted in a new direction and are not relying on contract as the basis for their strategy anymore. But even if they did consideration can come in many forms, it does not need to be a monetary payment. While I had some questions about consideration myself, I was never intending to suggest that monetary payments needed to be involved to form a binding contract. My apologizes if I was not clear in early posts.

**Comment by blakelapierre** [comment] 2017-03-03 01:01
@marctjones, to me, a pivot is a continuation of your path (albeit, yes, in a new direction). I didn't realize that much of the past claims here were disclaimed (it's kind of unclear at first glance which ones those are) in the abrupt pivot (is there an announcement thread?).

Can anyone produce instances of the US Government republishing copyrighted works with restrictive licenses, so that we can look at them for guidance? I can't recall an instance at the moment, but I do seem to remember seeing many disclaimers/warnings about being redirected to external sites which may offer content under different terms (some, even had/have "understanding confirmation" buttons).


__
After I wrote the above, I thought of https://opencatalog.darpa.mil/ (though, the earlier reported URI's now 404). I went to check if the code was offered under any license, but my browsers are warning me that the site is serving up a bad certificate (looks to be from an untrusted issuer).

**Comment by marctjones** [comment] 2017-03-03 01:24
@blakelapierre 

Publication is not generally relevant to who the copyright holder is. The copyright Office publishes some wonderfully readable [circulars](https://www.copyright.gov/circs/) to explain parts of copyright law. According to [Circular 1](https://www.copyright.gov/circs/circ01.pdf)

> Publication is no longer the key to obtaining federal copyright
as it was under the Copyright Act of 1909. 

But do note that: 
> Before 1978, federal copyright was generally secured
by the act of publication with notice of copyright, assuming
compliance with all other relevant statutory conditions. U.S.
works in the public domain on January 1, 1978, (for example,
works published without satisfying all conditions for securing
federal copyright under the Copyright Act of 1909) remain in
the public domain under the 1976 Copyright Act

While not exactly on point [Circular 14](https://www.copyright.gov/circs/circ14.pdf) explains how copyright works with derivative works generally. According to the copyright office:

> The copyright in a derivative work covers only the additions,
changes, or other new material appearing for the first time
in the work. Protection does not extend to any preexisting
material, that is, previously published or previously registered
works or works in the public domain or owned by a
third party.
>
> As a result, it is not possible to extend the length of
protection for a copyrighted work by creating a derivative
work. A work that has fallen into the public domain, that is,
a work that is no longer protected by copyright, is also an
underlying “work” from which derivative authorship may
be added, but the copyright in the derivative work will not
extend to the public domain material, and the use of the
public domain material in a derivative work will not prevent
anyone else from using the same public domain work for
another derivative work.

The USA.gov site also has a list of [Copyright Exceptions for U.S. Government Works](https://www.usa.gov/government-works#item-206099)

**Comment by marctjones** [comment] 2017-03-03 01:28
Someone suggested that [BRLCAD](https://brlcad.org/d/about) is an example of a work that is largely produced by the government and released under a FOSS license. You might want to check out issue #84 for that  discussion.

In any event I do believe that at least to the extent that this issue was originally questioning on the basis of using contract law as a legal tool to take advantage of a copyright license, that the issue is now moot.

**Comment by blakelapierre** [comment] 2017-03-03 17:28
It's too bad this project is being controlled by people with no apparent connection to the project or the US Government. I mean, really; I posted a blatant logical contradiction in the current strategy before going to sleep and the issue was closed before I woke up, without comment.

@marctjones, your [linked project](https://brlcad.org/d/about) specifically disclaims being a publication of the US Government (read the footer).

>In any event I do believe that at least to the extent that this issue was originally questioning on the basis of using contract law as a legal tool to take advantage of a copyright license, that the issue is now moot.

This issue was *never* originally about contracts. The explanation given in follow-up comments  was that contract law/theory was being used as a "bridge" to avoid the issue raised in the opener. However, the project has since, seemingly, "pivoted" away from using any contract law/theory; meaning, the original issue is still fully open, despite being sidetracked for a long time by contract talk.

**Comment by marctjones** [comment] 2017-03-03 18:45
@blakelapierre I believe that the change in legal tactic was announced here. The announcement also asked people to go read the new version of the CONTRIBUTING,md file which explains the theory for there current legal tack. The new legal tack was discussed and explained. You can see a more concise explanation provided by the project maintainers in the FAQ:

> The updated strategy in CONTRIBUTING.md does not attempt to attach licenses to Government-written code. Rather, the strategy attaches the license to copyrighted contributions by using the Developer Certificate of Origin (DCO) process and to Government-written code in countries where that code is eligible for copyright protections.

I am sorry my attempted explanation of why I disagreed that the contradiction you pointed out exists was not helpful. I believe you are referring to the contradiction you asserted to exist when you said: 

> I think the concern comes when the US Government republishes licensed code. I think we've established that all US Government publications are public domain, uncopyrightable, and/or unlicensable; meaning, anyone could do anything they'd like with any part of the publication they'd like. Now, we have reached a contradiction: anyone may freely "violate" any licensed code by virtue of their ownership of publications of the US Government, or, the US Government published a not public domain work.

I suggested that no such contradiction existed because my understanding is that copyright protection does not depend on publication and that the government can use copyrighted works under a license without depriving the copyright holders of their copyrights. I also pointed out several publications from the Copyright Office that would suggest that no such contradiction exists. Maybe I am missing something though. Would love to read any sources that suggest otherwise if you have a citation to them?

**Comment by blakelapierre** [comment] 2017-03-03 20:36
That is the contradiction.

>copyright protection does not depend on publication

It's also not relevant, in my view, as the US Government or its employees
do not have copyrights.

The situation, as I see it, will be, on publication of code under a
restrictive license (eg. those mentioned in the current [LICENSE proposal](
https://github.com/deptofdefense/code.mil/blob/master/Proposal/LICENSE.md)):

* The US Government has published a work
* People are restricted in their use of a US Government publication

Can you cite a statue that allows the US Government to publish
copy-restricted work, or an example of the US Government publishing
copy-restricted work?

**Comment by blakelapierre** [comment] 2017-03-03 20:40
To further illustrate the issue,

if the US Government publishes MIT license software, that publication is copy-restricted.

**Comment by marctjones** [comment] 2017-03-03 20:54
Yes you are correct if the U.S. government publishes a work containing MIT licensed code by a third party, then the publication as a whole would be at least in party restricted by copyrights.

I would suggest you look at the license that is asserted in the [COPYING](https://sourceforge.net/p/brlcad/code/HEAD/tree/brlcad/trunk/COPYING) file of BRL-CAD source code, instead of the disclaimer and license for the website.

But you might also want to check out [SELinux](https://www.nsa.gov/what-we-do/research/selinux/) which was originally a research project inside of the NSA in collaboration with outside contributors.

**Comment by tomberek** [comment] 2017-03-03 21:15
@marctjones That is correct.

@blakelapierre My interpretation is that the code created by government employees remain in the public domain, while contributions by third parties have copyright. Because public domain is the ultimate "recessive gene",  the de-facto license for a popular project will end up being the chosen license.

If the public doesn't like the license provided, they are free to fork the original commit (always in public domain) and republish/re-license at will. No contributor is forced to contribute to the government repo vice a fork.

Reopening this issue due to continued interest.

**Comment by marctjones** [comment] 2017-03-03 22:11
@blakelapierre I am still a little confused by your use of the word "publish" since you said it was not relevant to your position. If it is not relevant to the contradiction, then what difference does to exist of copyrights does it make that the government is publishing a work? 

If your concern is about the U.S. government's ability to hold copyright or its inability to acquire copyrights in works the government creates through its employees, then I would point you to [17 U.S.C. 105](https://www.law.cornell.edu/uscode/text/17/105):

> Sect. 105. Subject matter of copyright: United States Government works
>
> Copyright protection under this title [17 USCS Sects. 101 et seq.] is not available for any work of the United States Government, but the United States Government is not precluded from receiving and holding copyrights transferred to it by assignment, bequest, or otherwise.

It both states that copyrights are not granted to the federal governments in works created by the U.S. government and makes clear that the U.S. government can hold copyrights if acquire in other ways.

But the ability to hold copyright seems besides the point to me because this proposal does not seem to be for the government to acquire title to the copyrights of contributions of third parties. The proposal is to tactically use third party copyrights by republishing copyrighted code as part of a government work. The use of copyrighted material would in the typical cases make the government work a derivative work subject to the copyrights on the original work. The government (and anyone else for that matter) could then only publish the derivative work in accordance with the FOSS licensing terms the government is making use of the original work under. A very common way for a FOSS project to operate.

I am honestly confused as to what the contradiction you are concerned with at this point. It also seems clear from the [House Report for Section 105](https://www.law.cornell.edu/uscode/text/17/105?qt-us_code_temp_noupdates=1#qt-us_code_temp_noupdates) that this strategy would not be out of line with discretion that Congress (or at least the House committee) intended to granted to government agencies; even if this specific situation was not contemplated. But regardless the House Report makes clear that Section 105 was not intended to deprive private citizens of their copyright so the use of a work by the government would still be subject to the copyrights that existed in the work. Hence my suggestion that Circular 14 (while not authoritative since it is just a summary of the law) might be a good document to read if someone wanted to read about the Copyright Office's view on how the creation of a derivative work affects copyrights.

I believe at this point it is fair to say, that I simply disagree with the position I understand you to be taking. If you have additional citations beyond the ones I have provided I would love to read them, but I do not see the contradiction you are asserting exists. I have enjoyed the conversation though. Thank you!

@tomberek I would respectfully suggest that this issue has been resolved as the legal basis for your project is explained in the current version of the FAQ and Section 1 of CONTRIBUTING.md,  Good luck with your project. It is interesting to see an attempt at such a strong embrace of FOSS values from the DoD. Perhaps we will see some DoD folks at [LibrePlanet](https://www.libreplanet.org/2017/) this year.

**Comment by blakelapierre** [comment] 2017-03-04 01:06
>I am still a little confused by your use of the word "publish" since you said it was not relevant to your position.

@marctjones, you posited a "copyright protection" for a US Government work in an argument seeming to assert that the US Government takes no rights in some things it might publish (e.g. MIT licensed software):

>I suggested that no such contradiction existed because my understanding is that copyright protection does not depend on publication and that the government can use copyrighted works under a license without depriving the copyright holders of their copyrights.

What I indicated was not relevant, was whether or not copyright was related to publication, as US Government works are already barred from copyright.

>I am honestly confused as to what the contradiction you are concerned with at this point.

I'll reduce it.

Premises:
1. Congress may make no law abridging speech
2. US Government works may not be copyright
3. US Government may only conduct lawful activities
4. MIT license states certain speech must be maintained to copy

Contradiction:
1. US Government publishes MIT licensed software and demands all others must maintain certain speech to copy software.

If you have an example of restricted licensed software being actively published by the US Government, I would love to take a look at it. I'd also love to examine any statue that indicates the US Government can publish documents with copy-restricted licensing.

**Comment by marctjones** [comment] 2017-03-15 13:16
@tomberek I would suggest that since you reopened this issue because of continuing discussion and interest that you can close it now. 

I agree with @royfielding that not every government projects should be able to release FOSS code "without requiring a Copyright 101 course in every issue forum hosted by every government agency." It seems this thread when it was active degenerated into lectures about copyright law. At this point perhaps you should go with your attorney's advice and resolve this issue if you are satisfied that there is no "need to change the law" as the original issue was titled.

**Comment by blakelapierre** [comment] 2017-03-15 13:19
This issue should not be closed until the US Constitution is modified to
alleviate the identified contradiction or until the proposed licenses do
not restrict speech.

**Closed** 2017-08-30 19:37 UTC

**Comment by blakelapierre** [comment] 2017-08-30 21:00
What was this closed?

**Comment by jordangov** [comment] 2017-08-31 13:16
My apologies for not explaining this, but there has been no activity since Mar 15 and while it might be nice to have the US Constitution changed to alleviate any perceived contradictions, that is not the goal of this repository. We have legal counsel that has discussed the topic at length and we believe (via counsel) that we have a good path forward.

We thank everyone for the ongoing discussion and we invite any new issues for specific topics, concerns, or questions in new GitHub issues.

**Comment by blakelapierre** [comment] 2017-08-31 13:44
Please post your legal counsels' discussions and findings in relation to
this issue.

**Comment by jordangov** [comment] 2017-08-31 13:56
All of that information is posted by @shawoods in this thread above. This discussion is happening 100% in the open. The original topic was that we will need to change the laws in order to proceed, and that has not been our finding based on the citations and findings above. That is the reason for closing this specific GitHub issue.
